### ISSUE TITLE
KeyError: 'output_layers'

### ISSUE THREAD

**Issue by Mark-McCormick** [cognizant-ai-labs/autoinit#6]
While trying to use the AutoInit package for the first time I received the following message :

Traceback (most recent call last):

  File "C:\Users\mark_\AppData\Local\Temp/ipykernel_11124/4206825554.py", line 173, in <module>
    training_model = AutoInit().initialize_model(AFBR)

  File "C:\Users\mark_\miniconda3\lib\site-packages\autoinit\initializer\initialize_weights.py", line 247, in initialize_model
    for output_layer in self.model.get_config()['output_layers']:

KeyError: 'output_layers'

What does this message mean and how can I correct the error?

My model, called AFBR, is a simple Keras sequential MLP made of Input, Dense and Dropout layers.

I am using
Python 3.9.5
Tensorflow 2.7.0
Keras 2.7.0

**Comment by garrettbingham** [comment]
Hi Mark,

Can you try with TensorFlow 2.5 or 2.6?  We haven't tested 2.7 yet.

If downgrading TF doesn't help, can you share the code used to create your model as well as the output of `AFBR.get_config()`?

**Comment by garrettbingham** [comment]
I was able to reproduce the error.  The issue is that `Sequential` models do not have `output_layers` in the model config.  I'll push a fix shortly.

```
>>> model = keras.Sequential([
...     keras.Input(shape=(784)),
...     layers.Dense(32, activation='relu'),
...     layers.Dense(32, activation='relu'),
...     layers.Dense(32, activation='relu'),
...     layers.Dense(10),
... ])
>>> 
>>> model.get_config()['output_layers']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'output_layers'
>>> 
>>> model = tf.keras.Model(model.inputs, model.outputs)
>>> model.get_config()['output_layers']
[['dense_7', 0, 0]]
>>> 
```

**Comment by garrettbingham** [comment]
Hi Mark, can you try upgrading and see if it addresses the issue?  Make sure you are on `0.0.4`.

`pip install --upgrade git+https://github.com/cognizant-ai-labs/autoinit.git`

**Comment by Mark-McCormick** [comment]
Hi Garrett,
I installed the upgrade – thank you.
Yes, I am now on 0.0.4.
I installed tensorflow 2.5. My model works as it should.
Next I tested AutoInit.
The upgrade seems to have solved the KeyError: 'output_layers' problem.
After installing the upgrade I now have :
Traceback (most recent call last):
  File "C:\Users\mark_\AppData\Local\Temp/ipykernel_13676/659956421.py", line 179, in <module>
    training_model = AutoInit().initialize_model(AFBR)
  File "C:\Users\mark_\miniconda3\lib\site-packages\autoinit\initializer\initialize_weights.py", line 265, in initialize_model
    custom_objects.update({'CenteredUnitNorm': CenteredUnitNorm})
AttributeError: 'NoneType' object has no attribute 'update'

As requested, I am sharing the code below :

 
    X_train_mm = X_train_mm.astype(np.float32)  
    y_train_mm = y_train_mm.astype(np.float32)
    X_test_mm = X_test_mm.astype(np.float32)
    y_test_mm = y_test_mm.astype(np.float32)
    
    b = 4
    node=12
    lr = 0.0001  
    ep = 10
    do = 0.05 # drop out rate
    rho = 0.99 #Discounting factor for the history/coming gradient. Defaults to 0.9.
    mom = 0.05  # Momentum

    initializer = tensorflow.keras.initializers.TruncatedNormal(mean=0.0, stddev=0.1, seed = None) 

    ######## SEQUENTIAL MODEL ###############     
    AFBR = tensorflow.keras.Sequential()  
    AFBR.add(tensorflow.keras.layers.InputLayer(input_shape=(4,))) 
    AFBR.add(tensorflow.keras.layers.Dense(units=node, activation='relu', use_bias=True, kernel_initializer=initializer, bias_initializer = 'zeros'))
    AFBR.add(Dropout(do))
    AFBR.add(tensorflow.keras.layers.Dense(units=node, activation='relu', use_bias=True, kernel_initializer = initializer, bias_initializer = 'zeros'))
    AFBR.add(Dropout(do))
    AFBR.add(tensorflow.keras.layers.Dense(units=node, activation= 'relu', use_bias=True, kernel_initializer=initializer, bias_initializer = 'zeros'))
    AFBR.add(Dropout(do))
    AFBR.add(tensorflow.keras.layers.Dense(units=node, activation='relu', use_bias=True, kernel_initializer=initializer, bias_initializer = 'zeros')) 
    AFBR.add(tensorflow.keras.layers.Dense(units=1)) #,, activation='linear',input_dim=(1),input_shape=(step,)  , input_shape=(24,8)units=2, ,   
    print(AFBR.summary())
    
    metric= tensorflow.keras.metrics.MeanAbsoluteError(name='mean_absolute_error')
  
    AFBR.compile(optimizer=tensorflow.keras.optimizers.RMSprop(learning_rate=lr, rho=rho, momentum = mom, epsilon=0.0000001, centered= True), loss=tensorflow.keras.losses.MeanSquaredError(),  metrics = [metric]) 

    history = AFBR.fit(X_train_mm, y_train_mm, validation_data = (X_test_mm, y_test_mm), batch_size= int(b), epochs=ep,  shuffle = False, verbose=0) 

    from autoinit import AutoInit
    training_model = AutoInit().initialize_model(AFBR)

    test_scores = AFBR.evaluate(X_test_mm, y_test_mm , verbose=0) 
    print("Training loss (MSE):", history.history['loss'][0])
    print("Test loss (MSE):", history.history['val_loss'][1])

**Comment by garrettbingham** [comment]
Sorry about that! Upgrade once more to `0.0.5` please and try again.

**Comment by Mark-McCormick** [comment]
The AutoInit package is working now - thank you.
